#!/usr/bin/env bash
set -Eeuo pipefail

DEFAULT_IMAGE="ghcr.io/chenming0v0/chenxing-auth:latest"
DEFAULT_POSTGRES_IMAGE="postgres:16-alpine"
DEFAULT_REDIS_IMAGE="redis:7-alpine"
DEFAULT_PORT="3000"
DEFAULT_INSTALL_DIR="${PWD}/chenxing-auth"

stage() {
    printf '\n==> %s\n' "$1"
}

fail() {
    printf '\n安装失败: %s\n' "$1" >&2
    exit 1
}

on_error() {
    local status=$?
    printf '\n安装在第 %s 行失败，退出码 %s。Docker 的错误输出已保留在上方。\n' \
        "${BASH_LINENO[0]:-unknown}" "$status" >&2
    exit "$status"
}
trap on_error ERR

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

read_env_value() {
    local key="$1" line
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%$'\r'}"
        if [[ "$line" == "${key}="* ]]; then
            printf '%s' "${line#*=}"
            return 0
        fi
    done < "$ENV_FILE"
    return 0
}

env_has_key() {
    local key="$1" line
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%$'\r'}"
        [[ "$line" == "${key}="* ]] && return 0
    done < "$ENV_FILE"
    return 1
}

append_env_default() {
    local key="$1" value="$2"
    if ! env_has_key "$key"; then
        printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    fi
}

valid_port() {
    [[ "$1" =~ ^[0-9]+$ ]] && (( 10#$1 >= 1 && 10#$1 <= 65535 ))
}

generate_env() {
    local port="$1"
    umask 077
    cat > "$ENV_FILE" <<EOF
COMPOSE_PROJECT_NAME=chenxing-auth
CHENXING_IMAGE=${CHENXING_IMAGE}
POSTGRES_IMAGE=${POSTGRES_IMAGE}
REDIS_IMAGE=${REDIS_IMAGE}
REDIS_NAMESPACE=production
APP_HOST=0.0.0.0
APP_PORT=${port}
ADMIN_TOKEN=$(openssl rand -hex 32)
AUTH_ENCRYPTION_KEY=$(openssl rand -base64 32)
KEY_DIRECTORY=/var/lib/chenxing-auth/keys
KEY_ROTATION_GRACE_SECONDS=604800
KEY_ROTATION_SKEW_ALLOWANCE_SECONDS=3600
COOKIE_SECURE=true
POSTGRES_DB=chenxing_auth
POSTGRES_USER=chenxing
POSTGRES_PASSWORD=$(openssl rand -hex 32)
POSTGRES_RUNTIME_USER=chenxing_runtime
POSTGRES_RUNTIME_PASSWORD=$(openssl rand -hex 32)
SESSION_TTL_SECONDS=604800
AUDIT_ARCHIVE_ENABLED=false
AUDIT_RETENTION_DAYS=2555
RUST_LOG=chenxing_auth=info,tower_http=info
EOF
    chmod 600 "$ENV_FILE"
}

write_compose() {
    umask 022
    cat > "$COMPOSE_FILE" <<'YAML'
# Generated by the Chenxing remote installer. Persistent data lives in named volumes.
services:
  app:
    image: ${CHENXING_IMAGE}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 3000
      KEY_DIRECTORY: /var/lib/chenxing-auth/keys
      WEB_DIST_DIR: /usr/local/share/chenxing-auth/web/dist
      DATABASE_URL: postgres://${POSTGRES_RUNTIME_USER}:${POSTGRES_RUNTIME_PASSWORD}@postgres:5432/${POSTGRES_DB}
      MIGRATION_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      REDIS_NAMESPACE: ${REDIS_NAMESPACE}
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - chenxing-keys:/var/lib/chenxing-auth/keys
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:3000/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 12

  postgres:
    image: ${POSTGRES_IMAGE}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - chenxing-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 12

  redis:
    image: ${REDIS_IMAGE}
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - chenxing-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 12

volumes:
  chenxing-keys:
  chenxing-postgres:
  chenxing-redis:
YAML
}

compose() {
    docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

wait_for_postgres() {
    local attempt
    printf '等待 PostgreSQL 就绪'
    for attempt in $(seq 1 60); do
        if compose exec -T postgres pg_isready \
            -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
            printf ' 完成\n'
            return 0
        fi
        printf '.'
        sleep 2
    done
    printf '\n' >&2
    return 1
}

wait_for_application() {
    local attempt
    printf '等待辰星认证中枢启动'
    for attempt in $(seq 1 60); do
        if compose exec -T app curl --fail --silent --max-time 5 \
            http://127.0.0.1:3000/health/live >/dev/null 2>&1; then
            printf ' 完成\n'
            return 0
        fi
        printf '.'
        sleep 2
    done
    printf '\n' >&2
    return 1
}

IMAGE_OVERRIDE="${CHENXING_IMAGE:-}"
POSTGRES_IMAGE_OVERRIDE="${POSTGRES_IMAGE:-}"
REDIS_IMAGE_OVERRIDE="${REDIS_IMAGE:-}"
INSTALL_DIR="${CHENXING_INSTALL_DIR:-$DEFAULT_INSTALL_DIR}"
ENV_FILE="${INSTALL_DIR}/.env"
COMPOSE_FILE="${INSTALL_DIR}/compose.yml"
PREPARE_ONLY=false

if [[ "${1:-}" == "--prepare-only" ]]; then
    PREPARE_ONLY=true
elif [[ $# -ne 0 ]]; then
    fail "未知参数。直接运行脚本开始安装。"
fi

command_exists openssl || fail "缺少 openssl，无法生成部署密钥。"

CHENXING_IMAGE="${IMAGE_OVERRIDE:-$DEFAULT_IMAGE}"
POSTGRES_IMAGE="${POSTGRES_IMAGE_OVERRIDE:-$DEFAULT_POSTGRES_IMAGE}"
REDIS_IMAGE="${REDIS_IMAGE_OVERRIDE:-$DEFAULT_REDIS_IMAGE}"

stage "准备安装目录"
mkdir -p "$INSTALL_DIR"
printf '安装目录: %s\n' "$INSTALL_DIR"

if [[ -f "$ENV_FILE" ]]; then
    printf '检测到已有 .env，将保留数据库密码、Token 和加密密钥。\n'
    append_env_default COMPOSE_PROJECT_NAME chenxing-auth
    append_env_default CHENXING_IMAGE "$DEFAULT_IMAGE"
    append_env_default POSTGRES_IMAGE "$DEFAULT_POSTGRES_IMAGE"
    append_env_default REDIS_IMAGE "$DEFAULT_REDIS_IMAGE"
    append_env_default REDIS_NAMESPACE legacy
    chmod 600 "$ENV_FILE"
else
    port="${CHENXING_PORT:-}"
    if [[ -z "$port" && -t 0 ]]; then
        read -r -p "请输入对外端口 [${DEFAULT_PORT}]: " port
    fi
    port="${port:-$DEFAULT_PORT}"
    valid_port "$port" || fail "端口必须是 1 到 65535 之间的整数。"
    generate_env "$port"
    printf '已生成 .env，权限为 0600。\n'
fi

write_compose

CHENXING_IMAGE="${IMAGE_OVERRIDE:-$(read_env_value CHENXING_IMAGE)}"
POSTGRES_IMAGE="${POSTGRES_IMAGE_OVERRIDE:-$(read_env_value POSTGRES_IMAGE)}"
REDIS_IMAGE="${REDIS_IMAGE_OVERRIDE:-$(read_env_value REDIS_IMAGE)}"
export CHENXING_IMAGE POSTGRES_IMAGE REDIS_IMAGE
APP_PORT="$(read_env_value APP_PORT)"
APP_ISSUER="$(read_env_value APP_ISSUER)"
POSTGRES_DB="$(read_env_value POSTGRES_DB)"
POSTGRES_USER="$(read_env_value POSTGRES_USER)"
AUTH_ENCRYPTION_KEY="$(read_env_value AUTH_ENCRYPTION_KEY)"

valid_port "$APP_PORT" || fail ".env 中的 APP_PORT 无效。"
[[ -n "$CHENXING_IMAGE" && "$CHENXING_IMAGE" != *[[:space:]]* ]] || fail "辰星镜像名称无效。"
[[ -n "$POSTGRES_IMAGE" && "$POSTGRES_IMAGE" != *[[:space:]]* ]] || fail "PostgreSQL 镜像名称无效。"
[[ -n "$REDIS_IMAGE" && "$REDIS_IMAGE" != *[[:space:]]* ]] || fail "Redis 镜像名称无效。"
[[ -n "$POSTGRES_DB" && -n "$POSTGRES_USER" ]] || fail ".env 缺少 PostgreSQL 配置。"
if ! normalized_auth_key="$(
    printf '%s' "$AUTH_ENCRYPTION_KEY" \
        | openssl base64 -d -A 2>/dev/null \
        | openssl base64 -A
)"; then
    fail ".env 中的 AUTH_ENCRYPTION_KEY 不是有效 Base64。"
fi
[[ "$normalized_auth_key" == "$AUTH_ENCRYPTION_KEY" ]] \
    || fail ".env 中的 AUTH_ENCRYPTION_KEY 必须使用规范的标准 Base64 编码。"
decoded_key_bytes="$(printf '%s' "$AUTH_ENCRYPTION_KEY" | openssl base64 -d -A | wc -c)"
[[ "$decoded_key_bytes" -eq 32 ]] || fail ".env 中的 AUTH_ENCRYPTION_KEY 必须是 Base64 编码的 32 字节密钥。"

if [[ "$PREPARE_ONLY" == true ]]; then
    printf '已生成 %s 和 %s。\n' "$ENV_FILE" "$COMPOSE_FILE"
    exit 0
fi

command_exists docker || fail "缺少 Docker Engine，请先安装 Docker。"
docker compose version >/dev/null 2>&1 || fail "缺少 Docker Compose v2 插件。"
docker info >/dev/null 2>&1 || fail "无法连接 Docker daemon；请启动 Docker 或使用有权限的账号运行。"

stage "校验 Compose 配置"
compose config --quiet
printf 'Compose 配置有效。\n'

stage "拉取辰星认证中枢镜像"
printf '镜像: %s\n' "$CHENXING_IMAGE"
docker pull "$CHENXING_IMAGE"

stage "拉取 PostgreSQL 镜像"
printf '镜像: %s\n' "$POSTGRES_IMAGE"
docker pull "$POSTGRES_IMAGE"

stage "拉取 Redis 镜像"
printf '镜像: %s\n' "$REDIS_IMAGE"
docker pull "$REDIS_IMAGE"

stage "启动 PostgreSQL 和 Redis"
compose up -d postgres redis
wait_for_postgres || fail "PostgreSQL 未能在规定时间内就绪。"

stage "执行数据库迁移"
compose run --rm app migrate

stage "启动辰星认证中枢"
compose up -d app
if ! wait_for_application; then
    compose ps
    compose logs app
    fail "应用未能在规定时间内就绪。"
fi

stage "部署完成"
compose ps
cat <<EOF

访问地址: http://服务器地址:${APP_PORT}
安装目录: ${INSTALL_DIR}

新生成的 .env 不包含 APP_ISSUER。数据库尚未设置 Issuer 时，服务运行在保护模式：
健康检查和静态前端保持可用；不存在 Owner 时可公开初始化首个、固定为 ID=1 的 Owner，
该 Owner 可以登录并进入管理设置。注册、普通用户创建、管理员/Owner 创建保持关闭；
只有依赖正式 Issuer 的 OAuth/OIDC、Discovery、JWKS 和外部登录路由关闭。

请先完成首个 Owner 初始化，再由 Owner 在管理设置中写入固定的 HTTPS Issuer。
写入会保存到 PostgreSQL app_settings，并在当前进程热更新；不能从请求 Host 或代理头推导。
ADMIN_TOKEN 保留为管理 API 的恢复通道（为空时仍遵守管理 API 的禁用规则）。
管理员 Token 和全部随机密钥只保存在 ${ENV_FILE}，请备份并保持私密。
EOF
if [[ -n "$APP_ISSUER" ]]; then
    printf '%s\n' '检测到旧环境中的 APP_ISSUER；它仅按兼容规则在数据库没有 Issuer 时导入，数据库设置优先。'
fi
