-- Replace the UUID user key with a database-generated integer while preserving existing rows.
ALTER TABLE users
    ADD COLUMN generated_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE admins
    ADD COLUMN generated_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE user_consents
    ADD COLUMN generated_user_id BIGINT;
UPDATE user_consents AS c
SET generated_user_id = u.generated_id
FROM users AS u
WHERE c.user_id = u.id;
ALTER TABLE user_consents
    ALTER COLUMN generated_user_id SET NOT NULL;

ALTER TABLE user_sessions
    ADD COLUMN generated_user_id BIGINT;
UPDATE user_sessions AS s
SET generated_user_id = u.generated_id
FROM users AS u
WHERE s.user_id = u.id;
ALTER TABLE user_sessions
    ALTER COLUMN generated_user_id SET NOT NULL;

ALTER TABLE oauth_clients
    ADD COLUMN generated_owner_user_id BIGINT;
UPDATE oauth_clients AS c
SET generated_owner_user_id = u.generated_id
FROM users AS u
WHERE c.owner_user_id = u.id;

ALTER TABLE user_totp_factors
    ADD COLUMN generated_user_id BIGINT;
UPDATE user_totp_factors AS f
SET generated_user_id = u.generated_id
FROM users AS u
WHERE f.user_id = u.id;
ALTER TABLE user_totp_factors
    ALTER COLUMN generated_user_id SET NOT NULL;

ALTER TABLE user_passkeys
    ADD COLUMN generated_user_id BIGINT;
UPDATE user_passkeys AS p
SET generated_user_id = u.generated_id
FROM users AS u
WHERE p.user_id = u.id;
ALTER TABLE user_passkeys
    ALTER COLUMN generated_user_id SET NOT NULL;

ALTER TABLE user_consents
    DROP CONSTRAINT user_consents_pkey,
    DROP CONSTRAINT user_consents_user_id_fkey;
ALTER TABLE user_sessions
    DROP CONSTRAINT user_sessions_user_id_fkey;
ALTER TABLE oauth_clients
    DROP CONSTRAINT oauth_clients_owner_user_id_fkey;
ALTER TABLE user_totp_factors
    DROP CONSTRAINT user_totp_factors_pkey,
    DROP CONSTRAINT user_totp_factors_user_id_fkey;
ALTER TABLE user_passkeys
    DROP CONSTRAINT user_passkeys_user_id_fkey;
ALTER TABLE users
    DROP CONSTRAINT users_pkey;

ALTER TABLE admins
    DROP CONSTRAINT admins_pkey;

ALTER TABLE users
    RENAME COLUMN id TO legacy_uuid;
ALTER TABLE users
    RENAME COLUMN generated_id TO id;
ALTER TABLE users
    ALTER COLUMN legacy_uuid DROP NOT NULL;
ALTER TABLE users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id),
    ADD CONSTRAINT users_legacy_uuid_key UNIQUE (legacy_uuid);

ALTER TABLE admins
    RENAME COLUMN id TO legacy_uuid;
ALTER TABLE admins
    RENAME COLUMN generated_id TO id;
ALTER TABLE admins
    ALTER COLUMN legacy_uuid DROP NOT NULL;
ALTER TABLE admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id),
    ADD CONSTRAINT admins_legacy_uuid_key UNIQUE (legacy_uuid);
ALTER TABLE admins
    RENAME CONSTRAINT admins_email_key TO admins_username_key;

ALTER TABLE user_consents
    DROP COLUMN user_id;
ALTER TABLE user_consents
    RENAME COLUMN generated_user_id TO user_id;
ALTER TABLE user_consents
    ADD CONSTRAINT user_consents_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    ADD CONSTRAINT user_consents_pkey PRIMARY KEY (user_id, client_id);

ALTER TABLE user_sessions
    DROP COLUMN user_id;
ALTER TABLE user_sessions
    RENAME COLUMN generated_user_id TO user_id;
ALTER TABLE user_sessions
    ADD CONSTRAINT user_sessions_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
CREATE INDEX user_sessions_user_created_idx
    ON user_sessions (user_id, created_at DESC);

ALTER TABLE oauth_clients
    DROP COLUMN owner_user_id;
ALTER TABLE oauth_clients
    RENAME COLUMN generated_owner_user_id TO owner_user_id;
ALTER TABLE oauth_clients
    ADD CONSTRAINT oauth_clients_owner_user_id_fkey
        FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE;
CREATE INDEX oauth_clients_owner_user_id_idx
    ON oauth_clients (owner_user_id, created_at DESC);

ALTER TABLE user_totp_factors
    DROP COLUMN user_id;
ALTER TABLE user_totp_factors
    RENAME COLUMN generated_user_id TO user_id;
ALTER TABLE user_totp_factors
    ADD CONSTRAINT user_totp_factors_pkey PRIMARY KEY (user_id),
    ADD CONSTRAINT user_totp_factors_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE user_passkeys
    DROP COLUMN user_id;
ALTER TABLE user_passkeys
    RENAME COLUMN generated_user_id TO user_id;
ALTER TABLE user_passkeys
    ADD CONSTRAINT user_passkeys_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
CREATE INDEX user_passkeys_user_idx ON user_passkeys (user_id, created_at DESC);

SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    COALESCE((SELECT MAX(id) FROM users), 0) + 1,
    false
);

SELECT setval(
    pg_get_serial_sequence('admins', 'id'),
    COALESCE((SELECT MAX(id) FROM admins), 0) + 1,
    false
);
