-- Linked business-service accounts (Issue #706, CLtermux lane).
-- This table stores only the binding relationship and the validated display
-- snapshot returned by the provider. Public keys, private keys, and tokens are
-- never persisted: credentials live for the duration of a single request and
-- inbound service credentials are reduced to SHA-256 digests at config load.
-- Binding IDs are opaque, generated by the application, and never reused after
-- unbinding; uid values are permanently non-reusable per provider.
-- Concurrency consistency relies on the two unique constraints below, not on
-- check-then-insert application logic.
CREATE TABLE linked_accounts (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider_slug TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'service_account',
    uid TEXT NOT NULL,
    subject TEXT NOT NULL,
    binding_version INTEGER NOT NULL DEFAULT 1,
    account_status TEXT NOT NULL DEFAULT 'unknown',
    snapshot_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_attempt_at TIMESTAMPTZ,
    last_success_at TIMESTAMPTZ,
    sync_status TEXT NOT NULL DEFAULT 'never',
    sync_error TEXT,
    CONSTRAINT linked_accounts_id_shape_check CHECK (id <> '' AND char_length(id) <= 128),
    CONSTRAINT linked_accounts_uid_shape_check CHECK (uid <> '' AND char_length(uid) <= 255),
    CONSTRAINT linked_accounts_account_status_check CHECK (
        account_status IN ('active', 'disabled', 'missing', 'unknown')
    ),
    CONSTRAINT linked_accounts_sync_status_check CHECK (
        sync_status IN ('never', 'success', 'failed', 'unsupported')
    ),
    -- 协议上限：快照整体解压后 ≤128 KiB。JSONB 以文本形式计量，与入站
    -- serde 解析前的同一 128 KiB 边界保持一致。
    CONSTRAINT linked_accounts_snapshot_size_check CHECK (
        octet_length(snapshot_json::text) <= 131072
    ),
    CONSTRAINT linked_accounts_provider_uid_key UNIQUE (provider_slug, uid),
    CONSTRAINT linked_accounts_provider_user_key UNIQUE (provider_slug, user_id)
);
CREATE INDEX linked_accounts_user_id_idx ON linked_accounts (user_id);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE linked_accounts TO chenxing_runtime;