import { useState, type FormEvent } from 'react'
import { Activity, Database, Gauge, KeyRound, RefreshCw, Save, Server, ShieldCheck, UserCog, Users } from 'lucide-react'
import { users } from '../data'
import { ConsoleLayout } from '../components/shells'
import { Badge, Button, Field, HudPanel, Icon, Notice, PageHeader } from '../components/ui'

export function AdminDashboard() {
  return <ConsoleLayout><PageHeader eyebrow="ADMIN / DASHBOARD" title="系统仪表盘" description="认证中枢的运行状态、规模和最近管理活动。" action={<Badge tone="success"><span className="chenxing-status-dot" />系统正常</Badge>} /><div className="stat-grid"><HudPanel className="stat-panel"><header><span>注册用户</span><Users className="stat-icon" size={19} /></header><h2>1,284</h2><footer><span>较上月 +12.8%</span><Badge tone="success">GROWING</Badge></footer></HudPanel><HudPanel className="stat-panel"><header><span>今日认证</span><Activity className="stat-icon" size={19} /></header><h2>8,492</h2><footer><span>成功率 99.7%</span><Badge tone="success">HEALTHY</Badge></footer></HudPanel><HudPanel className="stat-panel"><header><span>OAuth 客户端</span><KeyRound className="stat-icon" size={19} /></header><h2>76</h2><footer><span>活跃 71 个</span><Badge>ACTIVE</Badge></footer></HudPanel></div><div className="content-grid grid-2"><HudPanel><div className="panel-heading"><div><h2>服务状态</h2><p>核心依赖的实时健康检查</p></div><RefreshCw size={18} color="var(--chenxing-cyan)" /></div><div className="list-stack"><div className="list-row"><div><strong>认证 API</strong><small>请求延迟 P95 · 42 ms</small></div><Badge tone="success">正常</Badge></div><div className="list-row"><div><strong>PostgreSQL</strong><small>连接池 · 8 / 32</small></div><Badge tone="success">正常</Badge></div><div className="list-row"><div><strong>Redis 状态</strong><small>缓存命中率 · 96.2%</small></div><Badge tone="success">正常</Badge></div><div className="list-row"><div><strong>签名密钥</strong><small>当前 kid · key-2026-07</small></div><Badge tone="warning">待轮换</Badge></div></div></HudPanel><HudPanel><div className="panel-heading"><div><h2>今日趋势</h2><p>过去 24 小时认证请求</p></div><Gauge size={18} color="var(--chenxing-cyan)" /></div><div className="chart-placeholder"><div className="chart-bars">{[42, 58, 45, 72, 66, 84, 61, 78, 91, 74, 86, 96].map((height, index) => <span style={{ height: `${height}%` }} key={index} />)}</div><div className="chart-axis"><span>00:00</span><span>12:00</span><span>现在</span></div></div></HudPanel></div></ConsoleLayout>
}

export function AdminUsers() {
  const [query, setQuery] = useState('')
  const filtered = users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase()))
  return <ConsoleLayout><PageHeader eyebrow="ADMIN / USERS" title="用户管理" description="搜索用户、查看身份状态和执行受权限保护的管理动作。" action={<Button variant="ghost" icon="download">导出审计</Button>} /><HudPanel><div className="panel-heading"><div><h2>用户目录</h2><p>共 {filtered.length} 条可见记录</p></div><div className="table-toolbar"><input className="search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索姓名或邮箱" /><Button variant="ghost" icon="users">筛选</Button></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>加入时间</th><th>最近活动</th><th>操作</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.email}><td><div className="table-person"><span className="avatar-button">{user.name[0]}</span><span><strong>{user.name}</strong><small>{user.email}</small></span></div></td><td><span className="code-text">{user.role}</span></td><td><Badge tone={user.status === '正常' ? 'success' : 'warning'}>{user.status}</Badge></td><td>{user.joined}</td><td>{user.lastSeen}</td><td><Button variant="ghost" icon="more-horizontal" aria-label={`管理 ${user.name}`}>管理</Button></td></tr>)}</tbody></table></div>{filtered.length === 0 && <div className="empty-state"><Users size={24} /><strong>没有匹配用户</strong><span>调整搜索关键词后重试。</span></div>}</HudPanel></ConsoleLayout>
}

export function AdminSettings() {
  const [saved, setSaved] = useState(false)
  const [maintenance, setMaintenance] = useState(false)
  const [registration, setRegistration] = useState(true)
  const submit = (event: FormEvent) => { event.preventDefault(); setSaved(true) }
  return <ConsoleLayout><PageHeader eyebrow="SYSTEM / SETTINGS" title="系统设置" description="调整认证中枢的公开策略、发行者信息和密钥状态。" action={<Badge><Server size={13} />CONFIGURATION</Badge>} /><div className="content-grid grid-2"><HudPanel><div className="panel-heading"><div><h2>基础配置</h2><p>协议响应使用的稳定配置值。</p></div><Database size={18} color="var(--chenxing-cyan)" /></div>{saved && <div className="auth-feedback"><Notice tone="success">演示模式：系统配置已记录，等待管理 API 接入。</Notice></div>}<form className="auth-form" onSubmit={submit}><Field label="OIDC Issuer" defaultValue="https://auth.clya.top" hint="发行者不能从请求 Host 推导。" /><Field label="系统名称" defaultValue="辰星认证中枢" /><Field label="支持邮箱" type="email" defaultValue="support@clya.top" /><Button type="submit" icon="save">保存配置</Button></form></HudPanel><HudPanel><div className="panel-heading"><div><h2>运行策略</h2><p>高影响操作需要明确的状态确认。</p></div><ShieldCheck size={18} color="var(--chenxing-cyan)" /></div><div className="settings-list"><Toggle label="开放注册" description="允许新的用户创建通行证。" checked={registration} onChange={setRegistration} /><Toggle label="维护模式" description="暂停新的认证请求，仅保留管理入口。" checked={maintenance} onChange={setMaintenance} tone="warning" /><div className="list-row"><div><strong>管理权限模型</strong><small>AdminPermission · 最小权限</small></div><Badge tone="success">ENFORCED</Badge></div></div></HudPanel></div><HudPanel><div className="panel-heading"><div><h2>签名密钥</h2><p>私钥只存在于受保护的运行时目录。</p></div><KeyRound size={18} color="var(--chenxing-cyan)" /></div><div className="key-status"><div><span className="chenxing-label">ACTIVE KID</span><strong>key-2026-07</strong></div><Badge tone="success">验证窗口正常</Badge><Button variant="danger" icon="refresh-cw">计划轮换</Button></div></HudPanel></ConsoleLayout>
}

function Toggle({ label, description, checked, onChange, tone = 'cyan' }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void; tone?: 'cyan' | 'warning' }) {
  return <label className="toggle-row"><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} data-tone={tone} /></label>
}
