import { useState, type FormEvent } from 'react'
import { ArrowRight, Check, Code2, ExternalLink, FlaskConical, Globe2, KeyRound, ShieldCheck } from 'lucide-react'
import { apps } from '../../data'
import { ConsoleLayout } from '../../components/shells'
import { Badge, Button, CopyValue, Field, HudPanel, Icon, Notice, PageHeader } from '../../components/ui'

export function IntegratePage() {
  const [created, setCreated] = useState(false)
  const submit = (event: FormEvent) => { event.preventDefault(); setCreated(true) }
  return <ConsoleLayout><PageHeader eyebrow="DEVELOPER / INTEGRATE" title="接入应用" description="创建 OAuth 客户端，让你的产品使用辰星通行证完成登录。" action={<Badge><Code2 size={13} />OAuth 2.0 / OIDC</Badge>} /><div className="content-grid grid-2"><HudPanel><div className="panel-heading"><div><h2>创建 OAuth 应用</h2><p>先在本地完成配置，正式保存由 API 负责。</p></div><Globe2 size={18} color="var(--chenxing-cyan)" /></div>{created ? <div className="content-grid"><Notice tone="success">演示模式：客户端草稿已生成。Client Secret 只应在真实创建时返回一次。</Notice><div><span className="chenxing-label">Client ID</span><CopyValue value="cli_demo_8f31c2" /></div><div><span className="chenxing-label">Redirect URI</span><CopyValue value="https://your-app.example.com/oauth/callback" /></div><Button variant="ghost" icon="arrow-right" onClick={() => setCreated(false)}>创建另一个应用</Button></div> : <form className="auth-form" onSubmit={submit}><Field label="应用名称" placeholder="例如：星图工作台" required /><Field label="Redirect URI" placeholder="https://example.com/oauth/callback" hint="必须使用 HTTPS；本地开发可使用 localhost。" required /><label className="field"><span className="chenxing-label">应用描述</span><textarea placeholder="简要说明这个应用的用途。" /></label><Button type="submit" icon="rocket">生成客户端草稿</Button></form>}</HudPanel><HudPanel><div className="panel-heading"><div><h2>接入检查清单</h2><p>上线前确认这些协议边界。</p></div><ShieldCheck size={18} color="var(--chenxing-cyan)" /></div><div className="checklist"><div><Check size={15} /><span><strong>严格匹配 Redirect URI</strong><small>不使用未经设计的通配符。</small></span></div><div><Check size={15} /><span><strong>启用 PKCE</strong><small>浏览器和移动端必须绑定 verifier。</small></span></div><div><Check size={15} /><span><strong>只申请必要 Scope</strong><small>默认从 openid 开始，按需扩展。</small></span></div><div><Check size={15} /><span><strong>安全保存 Client Secret</strong><small>不要放入浏览器或普通日志。</small></span></div></div></HudPanel></div><HudPanel className="integrated-list"><div className="panel-heading"><div><h2>你的应用</h2><p>已创建的 OAuth 客户端</p></div><span className="chenxing-mono code-text">{apps.length} / 3 CLIENTS</span></div><div className="list-stack">{apps.map((app) => <div className="list-row" key={app.clientId}><div><strong>{app.name}</strong><small>{app.redirect}</small></div><div className="panel-actions"><Badge tone="success">{app.status}</Badge><Button variant="ghost" icon="arrow-up-right">管理</Button></div></div>)}</div></HudPanel></ConsoleLayout>
}

export function PlaygroundPage() {
  const [submitted, setSubmitted] = useState(false)
  const [scope, setScope] = useState('openid profile email')
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(true) }
  return <ConsoleLayout><PageHeader eyebrow="DEVELOPER / PLAYGROUND" title="授权测试" description="在不离开控制台的情况下检查 Authorization Code + PKCE 流程。" action={<Badge tone="warning"><FlaskConical size={13} />测试环境</Badge>} /><div className="content-grid grid-2"><HudPanel><div className="panel-heading"><div><h2>生成测试请求</h2><p>参数仅用于当前演示，不会发送到后端。</p></div><KeyRound size={18} color="var(--chenxing-cyan)" /></div><form className="auth-form" onSubmit={submit}><label className="field"><span className="chenxing-label">客户端</span><select defaultValue="cli_local_5f2d"><option>本地 Playground · cli_local_5f2d</option><option>星图工作台 · cli_xingtu_7a18</option></select></label><Field label="Redirect URI" defaultValue="http://localhost:5175/oauth/callback" /><Field label="Scope" value={scope} onChange={(event) => setScope(event.target.value)} hint="用空格分隔，例如：openid profile email" /><Button type="submit" icon="send">生成授权 URL</Button></form></HudPanel><HudPanel><div className="panel-heading"><div><h2>当前流程</h2><p>标准 Authorization Code 流程</p></div><span className="chenxing-chip">PKCE S256</span></div><div className="flow-steps"><div className="flow-step is-done"><span>01</span><div><strong>生成 state / verifier</strong><small>防止请求伪造与授权码注入</small></div></div><div className="flow-step is-done"><span>02</span><div><strong>打开授权端点</strong><small>携带 client_id、scope 和 redirect_uri</small></div></div><div className="flow-step"><span>03</span><div><strong>交换授权码</strong><small>由后端使用 verifier 换取 Token</small></div></div></div></HudPanel></div>{submitted && <HudPanel className="playground-result"><div className="panel-heading"><div><h2>授权 URL 已生成</h2><p>请复制并在独立浏览器窗口打开。</p></div><Badge tone="success"><Check size={13} />READY</Badge></div><CopyValue value={`http://localhost:3000/oauth/authorize?client_id=cli_local_5f2d&scope=${encodeURIComponent(scope)}&response_type=code`} /><div className="notice notice-warning"><Icon name="circle-alert" size={17} />测试结果依赖后端 OAuth 端点和一次性状态存储，详见 API issue。</div></HudPanel>}</ConsoleLayout>
}
