import { useEffect, useState } from "react";
import { Search, ShieldAlert, UserRound } from "lucide-react";
import { api, AdminUser, errorMessage, formatDate } from "../../api";
import { Badge, PageFade } from "../../components/ui";

export default function Users() {
  const [users, setUsers] = useState<AdminUser[]>([]); const [search, setSearch] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setUsers((await api.adminUsers(search)).items); setError(null); } catch (value) { setError(errorMessage(value)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const toggle = async (user: AdminUser) => { try { await api.adminSetUserStatus(user.id, user.status === "active" ? "disabled" : "active"); await load(); } catch (value) { setError(errorMessage(value)); } };
  return <PageFade><div className="mb-6"><h1 className="flex items-center gap-2.5 text-xl font-bold text-white"><UserRound size={20} className="text-indigo-300" />用户管理</h1><p className="mt-1 text-sm text-slate-500">仅管理员 Session 可访问。数据来自管理员分页 API。</p></div><div className="mb-5 flex gap-3"><div className="field flex w-full max-w-sm items-center gap-2 rounded-xl px-3.5 py-2.5"><Search size={14} className="text-slate-600" /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void load(); }} placeholder="搜索邮箱或显示名称" className="w-full bg-transparent text-sm text-white placeholder:text-slate-600 focus:outline-none" /></div></div>{error && <div className="mb-5 rounded-xl border border-rose-400/20 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">{error}</div>}<div className="glass overflow-hidden rounded-3xl"><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead><tr className="border-b border-white/6 text-[11px] uppercase tracking-wider text-slate-600"><th className="px-6 py-4">用户</th><th className="px-4 py-4">状态</th><th className="px-4 py-4">注册时间</th><th className="px-4 py-4 text-right">操作</th></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="px-6 py-12 text-center text-sm text-slate-600">加载中…</td></tr> : users.map((user) => <tr key={user.id} className="border-b border-white/4 hover:bg-white/[0.025]"><td className="px-6 py-3.5"><div className="font-medium text-white">{user.display_name || "未设置名称"}</div><div className="text-xs text-slate-500">{user.email}</div></td><td className="px-4 py-3.5"><Badge tone={user.status === "active" ? "green" : "red"}>{user.status}</Badge></td><td className="px-4 py-3.5 text-xs text-slate-500">{formatDate(user.created_at)}</td><td className="px-4 py-3.5 text-right"><button onClick={() => void toggle(user)} className="rounded-lg p-2 text-slate-500 hover:bg-white/5 hover:text-white" title={user.status === "active" ? "冻结用户" : "解冻用户"}><ShieldAlert size={14} /></button></td></tr>)}{!loading && users.length === 0 && <tr><td colSpan={4} className="px-6 py-12 text-center text-sm text-slate-600">没有可显示的用户</td></tr>}</tbody></table></div></div></PageFade>;
}
